{
 "title": "Node Example",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1m,2m,5m,10m,30m,1h" },
   { "name": "hostname", "query": "hostname" }
  ]
 },
 "panels": [
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "LoadOne{hostname=\"$hostname\"}",
     "legendFormat": "LoadOne"
    },
    {
     "expr": "LoadFive{hostname=\"$hostname\"}",
     "legendFormat": "LoadFive"
    },
    {
     "expr": "LoadFifteen{hostname=\"$hostname\"}",
     "legendFormat": "LoadFifteen"
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "BytesSent{hostname=\"$hostname\",parameter=~\"(eth|ens|bond|br|tun)[0-9]+\"}",
     "legendFormat": "BytesSent[{{parameter}}]"
    },
    {
     "expr": "-BytesRecv{hostname=\"$hostname\",parameter=~\"(eth|ens|bond|br|tun)[0-9]+\"}",
     "legendFormat": "BytesRecv[{{parameter}}]"
    }
   ]
  },
  {
   "title": "GPU utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "gpu_utilization{hostname=\"$hostname\",parameter=~\"gpu.*\"} * 100",
     "legendFormat": "{{parameter}}"
    }
   ]
  }
 ]
}